// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: linear_model.proto

#ifndef PROTOBUF_INCLUDED_linear_5fmodel_2eproto
#define PROTOBUF_INCLUDED_linear_5fmodel_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_linear_5fmodel_2eproto 

namespace protobuf_linear_5fmodel_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[11];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_linear_5fmodel_2eproto
namespace perceptronix {
class DenseBinomialPerceptronProto;
class DenseBinomialPerceptronProtoDefaultTypeInternal;
extern DenseBinomialPerceptronProtoDefaultTypeInternal _DenseBinomialPerceptronProto_default_instance_;
class DenseInnerTableProto;
class DenseInnerTableProtoDefaultTypeInternal;
extern DenseInnerTableProtoDefaultTypeInternal _DenseInnerTableProto_default_instance_;
class DenseMultinomialPerceptronProto;
class DenseMultinomialPerceptronProtoDefaultTypeInternal;
extern DenseMultinomialPerceptronProtoDefaultTypeInternal _DenseMultinomialPerceptronProto_default_instance_;
class SparseBinomialPerceptronProto;
class SparseBinomialPerceptronProtoDefaultTypeInternal;
extern SparseBinomialPerceptronProtoDefaultTypeInternal _SparseBinomialPerceptronProto_default_instance_;
class SparseBinomialPerceptronProto_TableEntry_DoNotUse;
class SparseBinomialPerceptronProto_TableEntry_DoNotUseDefaultTypeInternal;
extern SparseBinomialPerceptronProto_TableEntry_DoNotUseDefaultTypeInternal _SparseBinomialPerceptronProto_TableEntry_DoNotUse_default_instance_;
class SparseDenseMultinomialPerceptronProto;
class SparseDenseMultinomialPerceptronProtoDefaultTypeInternal;
extern SparseDenseMultinomialPerceptronProtoDefaultTypeInternal _SparseDenseMultinomialPerceptronProto_default_instance_;
class SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse;
class SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUseDefaultTypeInternal;
extern SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUseDefaultTypeInternal _SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse_default_instance_;
class SparseInnerTableProto;
class SparseInnerTableProtoDefaultTypeInternal;
extern SparseInnerTableProtoDefaultTypeInternal _SparseInnerTableProto_default_instance_;
class SparseInnerTableProto_TableEntry_DoNotUse;
class SparseInnerTableProto_TableEntry_DoNotUseDefaultTypeInternal;
extern SparseInnerTableProto_TableEntry_DoNotUseDefaultTypeInternal _SparseInnerTableProto_TableEntry_DoNotUse_default_instance_;
class SparseMultinomialPerceptronProto;
class SparseMultinomialPerceptronProtoDefaultTypeInternal;
extern SparseMultinomialPerceptronProtoDefaultTypeInternal _SparseMultinomialPerceptronProto_default_instance_;
class SparseMultinomialPerceptronProto_TableEntry_DoNotUse;
class SparseMultinomialPerceptronProto_TableEntry_DoNotUseDefaultTypeInternal;
extern SparseMultinomialPerceptronProto_TableEntry_DoNotUseDefaultTypeInternal _SparseMultinomialPerceptronProto_TableEntry_DoNotUse_default_instance_;
}  // namespace perceptronix
namespace google {
namespace protobuf {
template<> ::perceptronix::DenseBinomialPerceptronProto* Arena::CreateMaybeMessage<::perceptronix::DenseBinomialPerceptronProto>(Arena*);
template<> ::perceptronix::DenseInnerTableProto* Arena::CreateMaybeMessage<::perceptronix::DenseInnerTableProto>(Arena*);
template<> ::perceptronix::DenseMultinomialPerceptronProto* Arena::CreateMaybeMessage<::perceptronix::DenseMultinomialPerceptronProto>(Arena*);
template<> ::perceptronix::SparseBinomialPerceptronProto* Arena::CreateMaybeMessage<::perceptronix::SparseBinomialPerceptronProto>(Arena*);
template<> ::perceptronix::SparseBinomialPerceptronProto_TableEntry_DoNotUse* Arena::CreateMaybeMessage<::perceptronix::SparseBinomialPerceptronProto_TableEntry_DoNotUse>(Arena*);
template<> ::perceptronix::SparseDenseMultinomialPerceptronProto* Arena::CreateMaybeMessage<::perceptronix::SparseDenseMultinomialPerceptronProto>(Arena*);
template<> ::perceptronix::SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse* Arena::CreateMaybeMessage<::perceptronix::SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse>(Arena*);
template<> ::perceptronix::SparseInnerTableProto* Arena::CreateMaybeMessage<::perceptronix::SparseInnerTableProto>(Arena*);
template<> ::perceptronix::SparseInnerTableProto_TableEntry_DoNotUse* Arena::CreateMaybeMessage<::perceptronix::SparseInnerTableProto_TableEntry_DoNotUse>(Arena*);
template<> ::perceptronix::SparseMultinomialPerceptronProto* Arena::CreateMaybeMessage<::perceptronix::SparseMultinomialPerceptronProto>(Arena*);
template<> ::perceptronix::SparseMultinomialPerceptronProto_TableEntry_DoNotUse* Arena::CreateMaybeMessage<::perceptronix::SparseMultinomialPerceptronProto_TableEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace perceptronix {

// ===================================================================

class DenseBinomialPerceptronProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perceptronix.DenseBinomialPerceptronProto) */ {
 public:
  DenseBinomialPerceptronProto();
  virtual ~DenseBinomialPerceptronProto();

  DenseBinomialPerceptronProto(const DenseBinomialPerceptronProto& from);

  inline DenseBinomialPerceptronProto& operator=(const DenseBinomialPerceptronProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DenseBinomialPerceptronProto(DenseBinomialPerceptronProto&& from) noexcept
    : DenseBinomialPerceptronProto() {
    *this = ::std::move(from);
  }

  inline DenseBinomialPerceptronProto& operator=(DenseBinomialPerceptronProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DenseBinomialPerceptronProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DenseBinomialPerceptronProto* internal_default_instance() {
    return reinterpret_cast<const DenseBinomialPerceptronProto*>(
               &_DenseBinomialPerceptronProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DenseBinomialPerceptronProto* other);
  friend void swap(DenseBinomialPerceptronProto& a, DenseBinomialPerceptronProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DenseBinomialPerceptronProto* New() const final {
    return CreateMaybeMessage<DenseBinomialPerceptronProto>(NULL);
  }

  DenseBinomialPerceptronProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DenseBinomialPerceptronProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DenseBinomialPerceptronProto& from);
  void MergeFrom(const DenseBinomialPerceptronProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DenseBinomialPerceptronProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float table = 3;
  int table_size() const;
  void clear_table();
  static const int kTableFieldNumber = 3;
  float table(int index) const;
  void set_table(int index, float value);
  void add_table(float value);
  const ::google::protobuf::RepeatedField< float >&
      table() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_table();

  // optional string metadata = 1 [default = ""];
  bool has_metadata() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::std::string& metadata() const;
  void set_metadata(const ::std::string& value);
  #if LANG_CXX11
  void set_metadata(::std::string&& value);
  #endif
  void set_metadata(const char* value);
  void set_metadata(const char* value, size_t size);
  ::std::string* mutable_metadata();
  ::std::string* release_metadata();
  void set_allocated_metadata(::std::string* metadata);

  // required float bias = 2;
  bool has_bias() const;
  void clear_bias();
  static const int kBiasFieldNumber = 2;
  float bias() const;
  void set_bias(float value);

  // @@protoc_insertion_point(class_scope:perceptronix.DenseBinomialPerceptronProto)
 private:
  void set_has_metadata();
  void clear_has_metadata();
  void set_has_bias();
  void clear_has_bias();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< float > table_;
  ::google::protobuf::internal::ArenaStringPtr metadata_;
  float bias_;
  friend struct ::protobuf_linear_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SparseBinomialPerceptronProto_TableEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SparseBinomialPerceptronProto_TableEntry_DoNotUse, 
    ::std::string, float,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SparseBinomialPerceptronProto_TableEntry_DoNotUse, 
    ::std::string, float,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
    0 > SuperType;
  SparseBinomialPerceptronProto_TableEntry_DoNotUse();
  SparseBinomialPerceptronProto_TableEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SparseBinomialPerceptronProto_TableEntry_DoNotUse& other);
  static const SparseBinomialPerceptronProto_TableEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SparseBinomialPerceptronProto_TableEntry_DoNotUse*>(&_SparseBinomialPerceptronProto_TableEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SparseBinomialPerceptronProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perceptronix.SparseBinomialPerceptronProto) */ {
 public:
  SparseBinomialPerceptronProto();
  virtual ~SparseBinomialPerceptronProto();

  SparseBinomialPerceptronProto(const SparseBinomialPerceptronProto& from);

  inline SparseBinomialPerceptronProto& operator=(const SparseBinomialPerceptronProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SparseBinomialPerceptronProto(SparseBinomialPerceptronProto&& from) noexcept
    : SparseBinomialPerceptronProto() {
    *this = ::std::move(from);
  }

  inline SparseBinomialPerceptronProto& operator=(SparseBinomialPerceptronProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SparseBinomialPerceptronProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SparseBinomialPerceptronProto* internal_default_instance() {
    return reinterpret_cast<const SparseBinomialPerceptronProto*>(
               &_SparseBinomialPerceptronProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SparseBinomialPerceptronProto* other);
  friend void swap(SparseBinomialPerceptronProto& a, SparseBinomialPerceptronProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SparseBinomialPerceptronProto* New() const final {
    return CreateMaybeMessage<SparseBinomialPerceptronProto>(NULL);
  }

  SparseBinomialPerceptronProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SparseBinomialPerceptronProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SparseBinomialPerceptronProto& from);
  void MergeFrom(const SparseBinomialPerceptronProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SparseBinomialPerceptronProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, float> table = 3;
  int table_size() const;
  void clear_table();
  static const int kTableFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, float >&
      table() const;
  ::google::protobuf::Map< ::std::string, float >*
      mutable_table();

  // optional string metadata = 1 [default = ""];
  bool has_metadata() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::std::string& metadata() const;
  void set_metadata(const ::std::string& value);
  #if LANG_CXX11
  void set_metadata(::std::string&& value);
  #endif
  void set_metadata(const char* value);
  void set_metadata(const char* value, size_t size);
  ::std::string* mutable_metadata();
  ::std::string* release_metadata();
  void set_allocated_metadata(::std::string* metadata);

  // required float bias = 2;
  bool has_bias() const;
  void clear_bias();
  static const int kBiasFieldNumber = 2;
  float bias() const;
  void set_bias(float value);

  // @@protoc_insertion_point(class_scope:perceptronix.SparseBinomialPerceptronProto)
 private:
  void set_has_metadata();
  void clear_has_metadata();
  void set_has_bias();
  void clear_has_bias();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::MapField<
      SparseBinomialPerceptronProto_TableEntry_DoNotUse,
      ::std::string, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > table_;
  ::google::protobuf::internal::ArenaStringPtr metadata_;
  float bias_;
  friend struct ::protobuf_linear_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DenseInnerTableProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perceptronix.DenseInnerTableProto) */ {
 public:
  DenseInnerTableProto();
  virtual ~DenseInnerTableProto();

  DenseInnerTableProto(const DenseInnerTableProto& from);

  inline DenseInnerTableProto& operator=(const DenseInnerTableProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DenseInnerTableProto(DenseInnerTableProto&& from) noexcept
    : DenseInnerTableProto() {
    *this = ::std::move(from);
  }

  inline DenseInnerTableProto& operator=(DenseInnerTableProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DenseInnerTableProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DenseInnerTableProto* internal_default_instance() {
    return reinterpret_cast<const DenseInnerTableProto*>(
               &_DenseInnerTableProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DenseInnerTableProto* other);
  friend void swap(DenseInnerTableProto& a, DenseInnerTableProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DenseInnerTableProto* New() const final {
    return CreateMaybeMessage<DenseInnerTableProto>(NULL);
  }

  DenseInnerTableProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DenseInnerTableProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DenseInnerTableProto& from);
  void MergeFrom(const DenseInnerTableProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DenseInnerTableProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float table = 1;
  int table_size() const;
  void clear_table();
  static const int kTableFieldNumber = 1;
  float table(int index) const;
  void set_table(int index, float value);
  void add_table(float value);
  const ::google::protobuf::RepeatedField< float >&
      table() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_table();

  // @@protoc_insertion_point(class_scope:perceptronix.DenseInnerTableProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< float > table_;
  friend struct ::protobuf_linear_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SparseInnerTableProto_TableEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SparseInnerTableProto_TableEntry_DoNotUse, 
    ::std::string, float,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SparseInnerTableProto_TableEntry_DoNotUse, 
    ::std::string, float,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
    0 > SuperType;
  SparseInnerTableProto_TableEntry_DoNotUse();
  SparseInnerTableProto_TableEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SparseInnerTableProto_TableEntry_DoNotUse& other);
  static const SparseInnerTableProto_TableEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SparseInnerTableProto_TableEntry_DoNotUse*>(&_SparseInnerTableProto_TableEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SparseInnerTableProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perceptronix.SparseInnerTableProto) */ {
 public:
  SparseInnerTableProto();
  virtual ~SparseInnerTableProto();

  SparseInnerTableProto(const SparseInnerTableProto& from);

  inline SparseInnerTableProto& operator=(const SparseInnerTableProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SparseInnerTableProto(SparseInnerTableProto&& from) noexcept
    : SparseInnerTableProto() {
    *this = ::std::move(from);
  }

  inline SparseInnerTableProto& operator=(SparseInnerTableProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SparseInnerTableProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SparseInnerTableProto* internal_default_instance() {
    return reinterpret_cast<const SparseInnerTableProto*>(
               &_SparseInnerTableProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(SparseInnerTableProto* other);
  friend void swap(SparseInnerTableProto& a, SparseInnerTableProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SparseInnerTableProto* New() const final {
    return CreateMaybeMessage<SparseInnerTableProto>(NULL);
  }

  SparseInnerTableProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SparseInnerTableProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SparseInnerTableProto& from);
  void MergeFrom(const SparseInnerTableProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SparseInnerTableProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, float> table = 1;
  int table_size() const;
  void clear_table();
  static const int kTableFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, float >&
      table() const;
  ::google::protobuf::Map< ::std::string, float >*
      mutable_table();

  // @@protoc_insertion_point(class_scope:perceptronix.SparseInnerTableProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::MapField<
      SparseInnerTableProto_TableEntry_DoNotUse,
      ::std::string, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > table_;
  friend struct ::protobuf_linear_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DenseMultinomialPerceptronProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perceptronix.DenseMultinomialPerceptronProto) */ {
 public:
  DenseMultinomialPerceptronProto();
  virtual ~DenseMultinomialPerceptronProto();

  DenseMultinomialPerceptronProto(const DenseMultinomialPerceptronProto& from);

  inline DenseMultinomialPerceptronProto& operator=(const DenseMultinomialPerceptronProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DenseMultinomialPerceptronProto(DenseMultinomialPerceptronProto&& from) noexcept
    : DenseMultinomialPerceptronProto() {
    *this = ::std::move(from);
  }

  inline DenseMultinomialPerceptronProto& operator=(DenseMultinomialPerceptronProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DenseMultinomialPerceptronProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DenseMultinomialPerceptronProto* internal_default_instance() {
    return reinterpret_cast<const DenseMultinomialPerceptronProto*>(
               &_DenseMultinomialPerceptronProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(DenseMultinomialPerceptronProto* other);
  friend void swap(DenseMultinomialPerceptronProto& a, DenseMultinomialPerceptronProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DenseMultinomialPerceptronProto* New() const final {
    return CreateMaybeMessage<DenseMultinomialPerceptronProto>(NULL);
  }

  DenseMultinomialPerceptronProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DenseMultinomialPerceptronProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DenseMultinomialPerceptronProto& from);
  void MergeFrom(const DenseMultinomialPerceptronProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DenseMultinomialPerceptronProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .perceptronix.DenseInnerTableProto table = 4;
  int table_size() const;
  void clear_table();
  static const int kTableFieldNumber = 4;
  ::perceptronix::DenseInnerTableProto* mutable_table(int index);
  ::google::protobuf::RepeatedPtrField< ::perceptronix::DenseInnerTableProto >*
      mutable_table();
  const ::perceptronix::DenseInnerTableProto& table(int index) const;
  ::perceptronix::DenseInnerTableProto* add_table();
  const ::google::protobuf::RepeatedPtrField< ::perceptronix::DenseInnerTableProto >&
      table() const;

  // optional string metadata = 1 [default = ""];
  bool has_metadata() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::std::string& metadata() const;
  void set_metadata(const ::std::string& value);
  #if LANG_CXX11
  void set_metadata(::std::string&& value);
  #endif
  void set_metadata(const char* value);
  void set_metadata(const char* value, size_t size);
  ::std::string* mutable_metadata();
  ::std::string* release_metadata();
  void set_allocated_metadata(::std::string* metadata);

  // required .perceptronix.DenseInnerTableProto bias = 3;
  bool has_bias() const;
  void clear_bias();
  static const int kBiasFieldNumber = 3;
  private:
  const ::perceptronix::DenseInnerTableProto& _internal_bias() const;
  public:
  const ::perceptronix::DenseInnerTableProto& bias() const;
  ::perceptronix::DenseInnerTableProto* release_bias();
  ::perceptronix::DenseInnerTableProto* mutable_bias();
  void set_allocated_bias(::perceptronix::DenseInnerTableProto* bias);

  // required uint32 inner_size = 2;
  bool has_inner_size() const;
  void clear_inner_size();
  static const int kInnerSizeFieldNumber = 2;
  ::google::protobuf::uint32 inner_size() const;
  void set_inner_size(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:perceptronix.DenseMultinomialPerceptronProto)
 private:
  void set_has_metadata();
  void clear_has_metadata();
  void set_has_inner_size();
  void clear_has_inner_size();
  void set_has_bias();
  void clear_has_bias();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::perceptronix::DenseInnerTableProto > table_;
  ::google::protobuf::internal::ArenaStringPtr metadata_;
  ::perceptronix::DenseInnerTableProto* bias_;
  ::google::protobuf::uint32 inner_size_;
  friend struct ::protobuf_linear_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse, 
    ::std::string, ::perceptronix::DenseInnerTableProto,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse, 
    ::std::string, ::perceptronix::DenseInnerTableProto,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse();
  SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse& other);
  static const SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse*>(&_SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SparseDenseMultinomialPerceptronProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perceptronix.SparseDenseMultinomialPerceptronProto) */ {
 public:
  SparseDenseMultinomialPerceptronProto();
  virtual ~SparseDenseMultinomialPerceptronProto();

  SparseDenseMultinomialPerceptronProto(const SparseDenseMultinomialPerceptronProto& from);

  inline SparseDenseMultinomialPerceptronProto& operator=(const SparseDenseMultinomialPerceptronProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SparseDenseMultinomialPerceptronProto(SparseDenseMultinomialPerceptronProto&& from) noexcept
    : SparseDenseMultinomialPerceptronProto() {
    *this = ::std::move(from);
  }

  inline SparseDenseMultinomialPerceptronProto& operator=(SparseDenseMultinomialPerceptronProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SparseDenseMultinomialPerceptronProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SparseDenseMultinomialPerceptronProto* internal_default_instance() {
    return reinterpret_cast<const SparseDenseMultinomialPerceptronProto*>(
               &_SparseDenseMultinomialPerceptronProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(SparseDenseMultinomialPerceptronProto* other);
  friend void swap(SparseDenseMultinomialPerceptronProto& a, SparseDenseMultinomialPerceptronProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SparseDenseMultinomialPerceptronProto* New() const final {
    return CreateMaybeMessage<SparseDenseMultinomialPerceptronProto>(NULL);
  }

  SparseDenseMultinomialPerceptronProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SparseDenseMultinomialPerceptronProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SparseDenseMultinomialPerceptronProto& from);
  void MergeFrom(const SparseDenseMultinomialPerceptronProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SparseDenseMultinomialPerceptronProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .perceptronix.DenseInnerTableProto> table = 4;
  int table_size() const;
  void clear_table();
  static const int kTableFieldNumber = 4;
  const ::google::protobuf::Map< ::std::string, ::perceptronix::DenseInnerTableProto >&
      table() const;
  ::google::protobuf::Map< ::std::string, ::perceptronix::DenseInnerTableProto >*
      mutable_table();

  // optional string metadata = 1 [default = ""];
  bool has_metadata() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::std::string& metadata() const;
  void set_metadata(const ::std::string& value);
  #if LANG_CXX11
  void set_metadata(::std::string&& value);
  #endif
  void set_metadata(const char* value);
  void set_metadata(const char* value, size_t size);
  ::std::string* mutable_metadata();
  ::std::string* release_metadata();
  void set_allocated_metadata(::std::string* metadata);

  // required .perceptronix.DenseInnerTableProto bias = 3;
  bool has_bias() const;
  void clear_bias();
  static const int kBiasFieldNumber = 3;
  private:
  const ::perceptronix::DenseInnerTableProto& _internal_bias() const;
  public:
  const ::perceptronix::DenseInnerTableProto& bias() const;
  ::perceptronix::DenseInnerTableProto* release_bias();
  ::perceptronix::DenseInnerTableProto* mutable_bias();
  void set_allocated_bias(::perceptronix::DenseInnerTableProto* bias);

  // required uint32 inner_size = 2;
  bool has_inner_size() const;
  void clear_inner_size();
  static const int kInnerSizeFieldNumber = 2;
  ::google::protobuf::uint32 inner_size() const;
  void set_inner_size(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:perceptronix.SparseDenseMultinomialPerceptronProto)
 private:
  void set_has_metadata();
  void clear_has_metadata();
  void set_has_inner_size();
  void clear_has_inner_size();
  void set_has_bias();
  void clear_has_bias();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::MapField<
      SparseDenseMultinomialPerceptronProto_TableEntry_DoNotUse,
      ::std::string, ::perceptronix::DenseInnerTableProto,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > table_;
  ::google::protobuf::internal::ArenaStringPtr metadata_;
  ::perceptronix::DenseInnerTableProto* bias_;
  ::google::protobuf::uint32 inner_size_;
  friend struct ::protobuf_linear_5fmodel_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SparseMultinomialPerceptronProto_TableEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SparseMultinomialPerceptronProto_TableEntry_DoNotUse, 
    ::std::string, ::perceptronix::SparseInnerTableProto,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SparseMultinomialPerceptronProto_TableEntry_DoNotUse, 
    ::std::string, ::perceptronix::SparseInnerTableProto,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  SparseMultinomialPerceptronProto_TableEntry_DoNotUse();
  SparseMultinomialPerceptronProto_TableEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SparseMultinomialPerceptronProto_TableEntry_DoNotUse& other);
  static const SparseMultinomialPerceptronProto_TableEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SparseMultinomialPerceptronProto_TableEntry_DoNotUse*>(&_SparseMultinomialPerceptronProto_TableEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SparseMultinomialPerceptronProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perceptronix.SparseMultinomialPerceptronProto) */ {
 public:
  SparseMultinomialPerceptronProto();
  virtual ~SparseMultinomialPerceptronProto();

  SparseMultinomialPerceptronProto(const SparseMultinomialPerceptronProto& from);

  inline SparseMultinomialPerceptronProto& operator=(const SparseMultinomialPerceptronProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SparseMultinomialPerceptronProto(SparseMultinomialPerceptronProto&& from) noexcept
    : SparseMultinomialPerceptronProto() {
    *this = ::std::move(from);
  }

  inline SparseMultinomialPerceptronProto& operator=(SparseMultinomialPerceptronProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SparseMultinomialPerceptronProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SparseMultinomialPerceptronProto* internal_default_instance() {
    return reinterpret_cast<const SparseMultinomialPerceptronProto*>(
               &_SparseMultinomialPerceptronProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(SparseMultinomialPerceptronProto* other);
  friend void swap(SparseMultinomialPerceptronProto& a, SparseMultinomialPerceptronProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SparseMultinomialPerceptronProto* New() const final {
    return CreateMaybeMessage<SparseMultinomialPerceptronProto>(NULL);
  }

  SparseMultinomialPerceptronProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SparseMultinomialPerceptronProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SparseMultinomialPerceptronProto& from);
  void MergeFrom(const SparseMultinomialPerceptronProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SparseMultinomialPerceptronProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .perceptronix.SparseInnerTableProto> table = 4;
  int table_size() const;
  void clear_table();
  static const int kTableFieldNumber = 4;
  const ::google::protobuf::Map< ::std::string, ::perceptronix::SparseInnerTableProto >&
      table() const;
  ::google::protobuf::Map< ::std::string, ::perceptronix::SparseInnerTableProto >*
      mutable_table();

  // optional string metadata = 1 [default = ""];
  bool has_metadata() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 1;
  const ::std::string& metadata() const;
  void set_metadata(const ::std::string& value);
  #if LANG_CXX11
  void set_metadata(::std::string&& value);
  #endif
  void set_metadata(const char* value);
  void set_metadata(const char* value, size_t size);
  ::std::string* mutable_metadata();
  ::std::string* release_metadata();
  void set_allocated_metadata(::std::string* metadata);

  // required .perceptronix.SparseInnerTableProto bias = 3;
  bool has_bias() const;
  void clear_bias();
  static const int kBiasFieldNumber = 3;
  private:
  const ::perceptronix::SparseInnerTableProto& _internal_bias() const;
  public:
  const ::perceptronix::SparseInnerTableProto& bias() const;
  ::perceptronix::SparseInnerTableProto* release_bias();
  ::perceptronix::SparseInnerTableProto* mutable_bias();
  void set_allocated_bias(::perceptronix::SparseInnerTableProto* bias);

  // required uint32 inner_size = 2;
  bool has_inner_size() const;
  void clear_inner_size();
  static const int kInnerSizeFieldNumber = 2;
  ::google::protobuf::uint32 inner_size() const;
  void set_inner_size(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:perceptronix.SparseMultinomialPerceptronProto)
 private:
  void set_has_metadata();
  void clear_has_metadata();
  void set_has_inner_size();
  void clear_has_inner_size();
  void set_has_bias();
  void clear_has_bias();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::MapField<
      SparseMultinomialPerceptronProto_TableEntry_DoNotUse,
      ::std::string, ::perceptronix::SparseInnerTableProto,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > table_;
  ::google::protobuf::internal::ArenaStringPtr metadata_;
  ::perceptronix::SparseInnerTableProto* bias_;
  ::google::protobuf::uint32 inner_size_;
  friend struct ::protobuf_linear_5fmodel_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DenseBinomialPerceptronProto

// optional string metadata = 1 [default = ""];
inline bool DenseBinomialPerceptronProto::has_metadata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DenseBinomialPerceptronProto::set_has_metadata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DenseBinomialPerceptronProto::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DenseBinomialPerceptronProto::clear_metadata() {
  metadata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_metadata();
}
inline const ::std::string& DenseBinomialPerceptronProto::metadata() const {
  // @@protoc_insertion_point(field_get:perceptronix.DenseBinomialPerceptronProto.metadata)
  return metadata_.GetNoArena();
}
inline void DenseBinomialPerceptronProto::set_metadata(const ::std::string& value) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:perceptronix.DenseBinomialPerceptronProto.metadata)
}
#if LANG_CXX11
inline void DenseBinomialPerceptronProto::set_metadata(::std::string&& value) {
  set_has_metadata();
  metadata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:perceptronix.DenseBinomialPerceptronProto.metadata)
}
#endif
inline void DenseBinomialPerceptronProto::set_metadata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:perceptronix.DenseBinomialPerceptronProto.metadata)
}
inline void DenseBinomialPerceptronProto::set_metadata(const char* value, size_t size) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:perceptronix.DenseBinomialPerceptronProto.metadata)
}
inline ::std::string* DenseBinomialPerceptronProto::mutable_metadata() {
  set_has_metadata();
  // @@protoc_insertion_point(field_mutable:perceptronix.DenseBinomialPerceptronProto.metadata)
  return metadata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DenseBinomialPerceptronProto::release_metadata() {
  // @@protoc_insertion_point(field_release:perceptronix.DenseBinomialPerceptronProto.metadata)
  if (!has_metadata()) {
    return NULL;
  }
  clear_has_metadata();
  return metadata_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DenseBinomialPerceptronProto::set_allocated_metadata(::std::string* metadata) {
  if (metadata != NULL) {
    set_has_metadata();
  } else {
    clear_has_metadata();
  }
  metadata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metadata);
  // @@protoc_insertion_point(field_set_allocated:perceptronix.DenseBinomialPerceptronProto.metadata)
}

// required float bias = 2;
inline bool DenseBinomialPerceptronProto::has_bias() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DenseBinomialPerceptronProto::set_has_bias() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DenseBinomialPerceptronProto::clear_has_bias() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DenseBinomialPerceptronProto::clear_bias() {
  bias_ = 0;
  clear_has_bias();
}
inline float DenseBinomialPerceptronProto::bias() const {
  // @@protoc_insertion_point(field_get:perceptronix.DenseBinomialPerceptronProto.bias)
  return bias_;
}
inline void DenseBinomialPerceptronProto::set_bias(float value) {
  set_has_bias();
  bias_ = value;
  // @@protoc_insertion_point(field_set:perceptronix.DenseBinomialPerceptronProto.bias)
}

// repeated float table = 3;
inline int DenseBinomialPerceptronProto::table_size() const {
  return table_.size();
}
inline void DenseBinomialPerceptronProto::clear_table() {
  table_.Clear();
}
inline float DenseBinomialPerceptronProto::table(int index) const {
  // @@protoc_insertion_point(field_get:perceptronix.DenseBinomialPerceptronProto.table)
  return table_.Get(index);
}
inline void DenseBinomialPerceptronProto::set_table(int index, float value) {
  table_.Set(index, value);
  // @@protoc_insertion_point(field_set:perceptronix.DenseBinomialPerceptronProto.table)
}
inline void DenseBinomialPerceptronProto::add_table(float value) {
  table_.Add(value);
  // @@protoc_insertion_point(field_add:perceptronix.DenseBinomialPerceptronProto.table)
}
inline const ::google::protobuf::RepeatedField< float >&
DenseBinomialPerceptronProto::table() const {
  // @@protoc_insertion_point(field_list:perceptronix.DenseBinomialPerceptronProto.table)
  return table_;
}
inline ::google::protobuf::RepeatedField< float >*
DenseBinomialPerceptronProto::mutable_table() {
  // @@protoc_insertion_point(field_mutable_list:perceptronix.DenseBinomialPerceptronProto.table)
  return &table_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SparseBinomialPerceptronProto

// optional string metadata = 1 [default = ""];
inline bool SparseBinomialPerceptronProto::has_metadata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SparseBinomialPerceptronProto::set_has_metadata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SparseBinomialPerceptronProto::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SparseBinomialPerceptronProto::clear_metadata() {
  metadata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_metadata();
}
inline const ::std::string& SparseBinomialPerceptronProto::metadata() const {
  // @@protoc_insertion_point(field_get:perceptronix.SparseBinomialPerceptronProto.metadata)
  return metadata_.GetNoArena();
}
inline void SparseBinomialPerceptronProto::set_metadata(const ::std::string& value) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:perceptronix.SparseBinomialPerceptronProto.metadata)
}
#if LANG_CXX11
inline void SparseBinomialPerceptronProto::set_metadata(::std::string&& value) {
  set_has_metadata();
  metadata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:perceptronix.SparseBinomialPerceptronProto.metadata)
}
#endif
inline void SparseBinomialPerceptronProto::set_metadata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:perceptronix.SparseBinomialPerceptronProto.metadata)
}
inline void SparseBinomialPerceptronProto::set_metadata(const char* value, size_t size) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:perceptronix.SparseBinomialPerceptronProto.metadata)
}
inline ::std::string* SparseBinomialPerceptronProto::mutable_metadata() {
  set_has_metadata();
  // @@protoc_insertion_point(field_mutable:perceptronix.SparseBinomialPerceptronProto.metadata)
  return metadata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SparseBinomialPerceptronProto::release_metadata() {
  // @@protoc_insertion_point(field_release:perceptronix.SparseBinomialPerceptronProto.metadata)
  if (!has_metadata()) {
    return NULL;
  }
  clear_has_metadata();
  return metadata_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SparseBinomialPerceptronProto::set_allocated_metadata(::std::string* metadata) {
  if (metadata != NULL) {
    set_has_metadata();
  } else {
    clear_has_metadata();
  }
  metadata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metadata);
  // @@protoc_insertion_point(field_set_allocated:perceptronix.SparseBinomialPerceptronProto.metadata)
}

// required float bias = 2;
inline bool SparseBinomialPerceptronProto::has_bias() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SparseBinomialPerceptronProto::set_has_bias() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SparseBinomialPerceptronProto::clear_has_bias() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SparseBinomialPerceptronProto::clear_bias() {
  bias_ = 0;
  clear_has_bias();
}
inline float SparseBinomialPerceptronProto::bias() const {
  // @@protoc_insertion_point(field_get:perceptronix.SparseBinomialPerceptronProto.bias)
  return bias_;
}
inline void SparseBinomialPerceptronProto::set_bias(float value) {
  set_has_bias();
  bias_ = value;
  // @@protoc_insertion_point(field_set:perceptronix.SparseBinomialPerceptronProto.bias)
}

// map<string, float> table = 3;
inline int SparseBinomialPerceptronProto::table_size() const {
  return table_.size();
}
inline void SparseBinomialPerceptronProto::clear_table() {
  table_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, float >&
SparseBinomialPerceptronProto::table() const {
  // @@protoc_insertion_point(field_map:perceptronix.SparseBinomialPerceptronProto.table)
  return table_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, float >*
SparseBinomialPerceptronProto::mutable_table() {
  // @@protoc_insertion_point(field_mutable_map:perceptronix.SparseBinomialPerceptronProto.table)
  return table_.MutableMap();
}

// -------------------------------------------------------------------

// DenseInnerTableProto

// repeated float table = 1;
inline int DenseInnerTableProto::table_size() const {
  return table_.size();
}
inline void DenseInnerTableProto::clear_table() {
  table_.Clear();
}
inline float DenseInnerTableProto::table(int index) const {
  // @@protoc_insertion_point(field_get:perceptronix.DenseInnerTableProto.table)
  return table_.Get(index);
}
inline void DenseInnerTableProto::set_table(int index, float value) {
  table_.Set(index, value);
  // @@protoc_insertion_point(field_set:perceptronix.DenseInnerTableProto.table)
}
inline void DenseInnerTableProto::add_table(float value) {
  table_.Add(value);
  // @@protoc_insertion_point(field_add:perceptronix.DenseInnerTableProto.table)
}
inline const ::google::protobuf::RepeatedField< float >&
DenseInnerTableProto::table() const {
  // @@protoc_insertion_point(field_list:perceptronix.DenseInnerTableProto.table)
  return table_;
}
inline ::google::protobuf::RepeatedField< float >*
DenseInnerTableProto::mutable_table() {
  // @@protoc_insertion_point(field_mutable_list:perceptronix.DenseInnerTableProto.table)
  return &table_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SparseInnerTableProto

// map<string, float> table = 1;
inline int SparseInnerTableProto::table_size() const {
  return table_.size();
}
inline void SparseInnerTableProto::clear_table() {
  table_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, float >&
SparseInnerTableProto::table() const {
  // @@protoc_insertion_point(field_map:perceptronix.SparseInnerTableProto.table)
  return table_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, float >*
SparseInnerTableProto::mutable_table() {
  // @@protoc_insertion_point(field_mutable_map:perceptronix.SparseInnerTableProto.table)
  return table_.MutableMap();
}

// -------------------------------------------------------------------

// DenseMultinomialPerceptronProto

// optional string metadata = 1 [default = ""];
inline bool DenseMultinomialPerceptronProto::has_metadata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DenseMultinomialPerceptronProto::set_has_metadata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DenseMultinomialPerceptronProto::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DenseMultinomialPerceptronProto::clear_metadata() {
  metadata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_metadata();
}
inline const ::std::string& DenseMultinomialPerceptronProto::metadata() const {
  // @@protoc_insertion_point(field_get:perceptronix.DenseMultinomialPerceptronProto.metadata)
  return metadata_.GetNoArena();
}
inline void DenseMultinomialPerceptronProto::set_metadata(const ::std::string& value) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:perceptronix.DenseMultinomialPerceptronProto.metadata)
}
#if LANG_CXX11
inline void DenseMultinomialPerceptronProto::set_metadata(::std::string&& value) {
  set_has_metadata();
  metadata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:perceptronix.DenseMultinomialPerceptronProto.metadata)
}
#endif
inline void DenseMultinomialPerceptronProto::set_metadata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:perceptronix.DenseMultinomialPerceptronProto.metadata)
}
inline void DenseMultinomialPerceptronProto::set_metadata(const char* value, size_t size) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:perceptronix.DenseMultinomialPerceptronProto.metadata)
}
inline ::std::string* DenseMultinomialPerceptronProto::mutable_metadata() {
  set_has_metadata();
  // @@protoc_insertion_point(field_mutable:perceptronix.DenseMultinomialPerceptronProto.metadata)
  return metadata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DenseMultinomialPerceptronProto::release_metadata() {
  // @@protoc_insertion_point(field_release:perceptronix.DenseMultinomialPerceptronProto.metadata)
  if (!has_metadata()) {
    return NULL;
  }
  clear_has_metadata();
  return metadata_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DenseMultinomialPerceptronProto::set_allocated_metadata(::std::string* metadata) {
  if (metadata != NULL) {
    set_has_metadata();
  } else {
    clear_has_metadata();
  }
  metadata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metadata);
  // @@protoc_insertion_point(field_set_allocated:perceptronix.DenseMultinomialPerceptronProto.metadata)
}

// required uint32 inner_size = 2;
inline bool DenseMultinomialPerceptronProto::has_inner_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DenseMultinomialPerceptronProto::set_has_inner_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DenseMultinomialPerceptronProto::clear_has_inner_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DenseMultinomialPerceptronProto::clear_inner_size() {
  inner_size_ = 0u;
  clear_has_inner_size();
}
inline ::google::protobuf::uint32 DenseMultinomialPerceptronProto::inner_size() const {
  // @@protoc_insertion_point(field_get:perceptronix.DenseMultinomialPerceptronProto.inner_size)
  return inner_size_;
}
inline void DenseMultinomialPerceptronProto::set_inner_size(::google::protobuf::uint32 value) {
  set_has_inner_size();
  inner_size_ = value;
  // @@protoc_insertion_point(field_set:perceptronix.DenseMultinomialPerceptronProto.inner_size)
}

// required .perceptronix.DenseInnerTableProto bias = 3;
inline bool DenseMultinomialPerceptronProto::has_bias() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DenseMultinomialPerceptronProto::set_has_bias() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DenseMultinomialPerceptronProto::clear_has_bias() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DenseMultinomialPerceptronProto::clear_bias() {
  if (bias_ != NULL) bias_->Clear();
  clear_has_bias();
}
inline const ::perceptronix::DenseInnerTableProto& DenseMultinomialPerceptronProto::_internal_bias() const {
  return *bias_;
}
inline const ::perceptronix::DenseInnerTableProto& DenseMultinomialPerceptronProto::bias() const {
  const ::perceptronix::DenseInnerTableProto* p = bias_;
  // @@protoc_insertion_point(field_get:perceptronix.DenseMultinomialPerceptronProto.bias)
  return p != NULL ? *p : *reinterpret_cast<const ::perceptronix::DenseInnerTableProto*>(
      &::perceptronix::_DenseInnerTableProto_default_instance_);
}
inline ::perceptronix::DenseInnerTableProto* DenseMultinomialPerceptronProto::release_bias() {
  // @@protoc_insertion_point(field_release:perceptronix.DenseMultinomialPerceptronProto.bias)
  clear_has_bias();
  ::perceptronix::DenseInnerTableProto* temp = bias_;
  bias_ = NULL;
  return temp;
}
inline ::perceptronix::DenseInnerTableProto* DenseMultinomialPerceptronProto::mutable_bias() {
  set_has_bias();
  if (bias_ == NULL) {
    auto* p = CreateMaybeMessage<::perceptronix::DenseInnerTableProto>(GetArenaNoVirtual());
    bias_ = p;
  }
  // @@protoc_insertion_point(field_mutable:perceptronix.DenseMultinomialPerceptronProto.bias)
  return bias_;
}
inline void DenseMultinomialPerceptronProto::set_allocated_bias(::perceptronix::DenseInnerTableProto* bias) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bias_;
  }
  if (bias) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bias = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bias, submessage_arena);
    }
    set_has_bias();
  } else {
    clear_has_bias();
  }
  bias_ = bias;
  // @@protoc_insertion_point(field_set_allocated:perceptronix.DenseMultinomialPerceptronProto.bias)
}

// repeated .perceptronix.DenseInnerTableProto table = 4;
inline int DenseMultinomialPerceptronProto::table_size() const {
  return table_.size();
}
inline void DenseMultinomialPerceptronProto::clear_table() {
  table_.Clear();
}
inline ::perceptronix::DenseInnerTableProto* DenseMultinomialPerceptronProto::mutable_table(int index) {
  // @@protoc_insertion_point(field_mutable:perceptronix.DenseMultinomialPerceptronProto.table)
  return table_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::perceptronix::DenseInnerTableProto >*
DenseMultinomialPerceptronProto::mutable_table() {
  // @@protoc_insertion_point(field_mutable_list:perceptronix.DenseMultinomialPerceptronProto.table)
  return &table_;
}
inline const ::perceptronix::DenseInnerTableProto& DenseMultinomialPerceptronProto::table(int index) const {
  // @@protoc_insertion_point(field_get:perceptronix.DenseMultinomialPerceptronProto.table)
  return table_.Get(index);
}
inline ::perceptronix::DenseInnerTableProto* DenseMultinomialPerceptronProto::add_table() {
  // @@protoc_insertion_point(field_add:perceptronix.DenseMultinomialPerceptronProto.table)
  return table_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::perceptronix::DenseInnerTableProto >&
DenseMultinomialPerceptronProto::table() const {
  // @@protoc_insertion_point(field_list:perceptronix.DenseMultinomialPerceptronProto.table)
  return table_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SparseDenseMultinomialPerceptronProto

// optional string metadata = 1 [default = ""];
inline bool SparseDenseMultinomialPerceptronProto::has_metadata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SparseDenseMultinomialPerceptronProto::set_has_metadata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SparseDenseMultinomialPerceptronProto::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SparseDenseMultinomialPerceptronProto::clear_metadata() {
  metadata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_metadata();
}
inline const ::std::string& SparseDenseMultinomialPerceptronProto::metadata() const {
  // @@protoc_insertion_point(field_get:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
  return metadata_.GetNoArena();
}
inline void SparseDenseMultinomialPerceptronProto::set_metadata(const ::std::string& value) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
}
#if LANG_CXX11
inline void SparseDenseMultinomialPerceptronProto::set_metadata(::std::string&& value) {
  set_has_metadata();
  metadata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
}
#endif
inline void SparseDenseMultinomialPerceptronProto::set_metadata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
}
inline void SparseDenseMultinomialPerceptronProto::set_metadata(const char* value, size_t size) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
}
inline ::std::string* SparseDenseMultinomialPerceptronProto::mutable_metadata() {
  set_has_metadata();
  // @@protoc_insertion_point(field_mutable:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
  return metadata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SparseDenseMultinomialPerceptronProto::release_metadata() {
  // @@protoc_insertion_point(field_release:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
  if (!has_metadata()) {
    return NULL;
  }
  clear_has_metadata();
  return metadata_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SparseDenseMultinomialPerceptronProto::set_allocated_metadata(::std::string* metadata) {
  if (metadata != NULL) {
    set_has_metadata();
  } else {
    clear_has_metadata();
  }
  metadata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metadata);
  // @@protoc_insertion_point(field_set_allocated:perceptronix.SparseDenseMultinomialPerceptronProto.metadata)
}

// required uint32 inner_size = 2;
inline bool SparseDenseMultinomialPerceptronProto::has_inner_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SparseDenseMultinomialPerceptronProto::set_has_inner_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SparseDenseMultinomialPerceptronProto::clear_has_inner_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SparseDenseMultinomialPerceptronProto::clear_inner_size() {
  inner_size_ = 0u;
  clear_has_inner_size();
}
inline ::google::protobuf::uint32 SparseDenseMultinomialPerceptronProto::inner_size() const {
  // @@protoc_insertion_point(field_get:perceptronix.SparseDenseMultinomialPerceptronProto.inner_size)
  return inner_size_;
}
inline void SparseDenseMultinomialPerceptronProto::set_inner_size(::google::protobuf::uint32 value) {
  set_has_inner_size();
  inner_size_ = value;
  // @@protoc_insertion_point(field_set:perceptronix.SparseDenseMultinomialPerceptronProto.inner_size)
}

// required .perceptronix.DenseInnerTableProto bias = 3;
inline bool SparseDenseMultinomialPerceptronProto::has_bias() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SparseDenseMultinomialPerceptronProto::set_has_bias() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SparseDenseMultinomialPerceptronProto::clear_has_bias() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SparseDenseMultinomialPerceptronProto::clear_bias() {
  if (bias_ != NULL) bias_->Clear();
  clear_has_bias();
}
inline const ::perceptronix::DenseInnerTableProto& SparseDenseMultinomialPerceptronProto::_internal_bias() const {
  return *bias_;
}
inline const ::perceptronix::DenseInnerTableProto& SparseDenseMultinomialPerceptronProto::bias() const {
  const ::perceptronix::DenseInnerTableProto* p = bias_;
  // @@protoc_insertion_point(field_get:perceptronix.SparseDenseMultinomialPerceptronProto.bias)
  return p != NULL ? *p : *reinterpret_cast<const ::perceptronix::DenseInnerTableProto*>(
      &::perceptronix::_DenseInnerTableProto_default_instance_);
}
inline ::perceptronix::DenseInnerTableProto* SparseDenseMultinomialPerceptronProto::release_bias() {
  // @@protoc_insertion_point(field_release:perceptronix.SparseDenseMultinomialPerceptronProto.bias)
  clear_has_bias();
  ::perceptronix::DenseInnerTableProto* temp = bias_;
  bias_ = NULL;
  return temp;
}
inline ::perceptronix::DenseInnerTableProto* SparseDenseMultinomialPerceptronProto::mutable_bias() {
  set_has_bias();
  if (bias_ == NULL) {
    auto* p = CreateMaybeMessage<::perceptronix::DenseInnerTableProto>(GetArenaNoVirtual());
    bias_ = p;
  }
  // @@protoc_insertion_point(field_mutable:perceptronix.SparseDenseMultinomialPerceptronProto.bias)
  return bias_;
}
inline void SparseDenseMultinomialPerceptronProto::set_allocated_bias(::perceptronix::DenseInnerTableProto* bias) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bias_;
  }
  if (bias) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bias = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bias, submessage_arena);
    }
    set_has_bias();
  } else {
    clear_has_bias();
  }
  bias_ = bias;
  // @@protoc_insertion_point(field_set_allocated:perceptronix.SparseDenseMultinomialPerceptronProto.bias)
}

// map<string, .perceptronix.DenseInnerTableProto> table = 4;
inline int SparseDenseMultinomialPerceptronProto::table_size() const {
  return table_.size();
}
inline void SparseDenseMultinomialPerceptronProto::clear_table() {
  table_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::perceptronix::DenseInnerTableProto >&
SparseDenseMultinomialPerceptronProto::table() const {
  // @@protoc_insertion_point(field_map:perceptronix.SparseDenseMultinomialPerceptronProto.table)
  return table_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::perceptronix::DenseInnerTableProto >*
SparseDenseMultinomialPerceptronProto::mutable_table() {
  // @@protoc_insertion_point(field_mutable_map:perceptronix.SparseDenseMultinomialPerceptronProto.table)
  return table_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SparseMultinomialPerceptronProto

// optional string metadata = 1 [default = ""];
inline bool SparseMultinomialPerceptronProto::has_metadata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SparseMultinomialPerceptronProto::set_has_metadata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SparseMultinomialPerceptronProto::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SparseMultinomialPerceptronProto::clear_metadata() {
  metadata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_metadata();
}
inline const ::std::string& SparseMultinomialPerceptronProto::metadata() const {
  // @@protoc_insertion_point(field_get:perceptronix.SparseMultinomialPerceptronProto.metadata)
  return metadata_.GetNoArena();
}
inline void SparseMultinomialPerceptronProto::set_metadata(const ::std::string& value) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:perceptronix.SparseMultinomialPerceptronProto.metadata)
}
#if LANG_CXX11
inline void SparseMultinomialPerceptronProto::set_metadata(::std::string&& value) {
  set_has_metadata();
  metadata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:perceptronix.SparseMultinomialPerceptronProto.metadata)
}
#endif
inline void SparseMultinomialPerceptronProto::set_metadata(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:perceptronix.SparseMultinomialPerceptronProto.metadata)
}
inline void SparseMultinomialPerceptronProto::set_metadata(const char* value, size_t size) {
  set_has_metadata();
  metadata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:perceptronix.SparseMultinomialPerceptronProto.metadata)
}
inline ::std::string* SparseMultinomialPerceptronProto::mutable_metadata() {
  set_has_metadata();
  // @@protoc_insertion_point(field_mutable:perceptronix.SparseMultinomialPerceptronProto.metadata)
  return metadata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SparseMultinomialPerceptronProto::release_metadata() {
  // @@protoc_insertion_point(field_release:perceptronix.SparseMultinomialPerceptronProto.metadata)
  if (!has_metadata()) {
    return NULL;
  }
  clear_has_metadata();
  return metadata_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SparseMultinomialPerceptronProto::set_allocated_metadata(::std::string* metadata) {
  if (metadata != NULL) {
    set_has_metadata();
  } else {
    clear_has_metadata();
  }
  metadata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), metadata);
  // @@protoc_insertion_point(field_set_allocated:perceptronix.SparseMultinomialPerceptronProto.metadata)
}

// required uint32 inner_size = 2;
inline bool SparseMultinomialPerceptronProto::has_inner_size() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SparseMultinomialPerceptronProto::set_has_inner_size() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SparseMultinomialPerceptronProto::clear_has_inner_size() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SparseMultinomialPerceptronProto::clear_inner_size() {
  inner_size_ = 0u;
  clear_has_inner_size();
}
inline ::google::protobuf::uint32 SparseMultinomialPerceptronProto::inner_size() const {
  // @@protoc_insertion_point(field_get:perceptronix.SparseMultinomialPerceptronProto.inner_size)
  return inner_size_;
}
inline void SparseMultinomialPerceptronProto::set_inner_size(::google::protobuf::uint32 value) {
  set_has_inner_size();
  inner_size_ = value;
  // @@protoc_insertion_point(field_set:perceptronix.SparseMultinomialPerceptronProto.inner_size)
}

// required .perceptronix.SparseInnerTableProto bias = 3;
inline bool SparseMultinomialPerceptronProto::has_bias() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SparseMultinomialPerceptronProto::set_has_bias() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SparseMultinomialPerceptronProto::clear_has_bias() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SparseMultinomialPerceptronProto::clear_bias() {
  if (bias_ != NULL) bias_->Clear();
  clear_has_bias();
}
inline const ::perceptronix::SparseInnerTableProto& SparseMultinomialPerceptronProto::_internal_bias() const {
  return *bias_;
}
inline const ::perceptronix::SparseInnerTableProto& SparseMultinomialPerceptronProto::bias() const {
  const ::perceptronix::SparseInnerTableProto* p = bias_;
  // @@protoc_insertion_point(field_get:perceptronix.SparseMultinomialPerceptronProto.bias)
  return p != NULL ? *p : *reinterpret_cast<const ::perceptronix::SparseInnerTableProto*>(
      &::perceptronix::_SparseInnerTableProto_default_instance_);
}
inline ::perceptronix::SparseInnerTableProto* SparseMultinomialPerceptronProto::release_bias() {
  // @@protoc_insertion_point(field_release:perceptronix.SparseMultinomialPerceptronProto.bias)
  clear_has_bias();
  ::perceptronix::SparseInnerTableProto* temp = bias_;
  bias_ = NULL;
  return temp;
}
inline ::perceptronix::SparseInnerTableProto* SparseMultinomialPerceptronProto::mutable_bias() {
  set_has_bias();
  if (bias_ == NULL) {
    auto* p = CreateMaybeMessage<::perceptronix::SparseInnerTableProto>(GetArenaNoVirtual());
    bias_ = p;
  }
  // @@protoc_insertion_point(field_mutable:perceptronix.SparseMultinomialPerceptronProto.bias)
  return bias_;
}
inline void SparseMultinomialPerceptronProto::set_allocated_bias(::perceptronix::SparseInnerTableProto* bias) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bias_;
  }
  if (bias) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bias = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bias, submessage_arena);
    }
    set_has_bias();
  } else {
    clear_has_bias();
  }
  bias_ = bias;
  // @@protoc_insertion_point(field_set_allocated:perceptronix.SparseMultinomialPerceptronProto.bias)
}

// map<string, .perceptronix.SparseInnerTableProto> table = 4;
inline int SparseMultinomialPerceptronProto::table_size() const {
  return table_.size();
}
inline void SparseMultinomialPerceptronProto::clear_table() {
  table_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::perceptronix::SparseInnerTableProto >&
SparseMultinomialPerceptronProto::table() const {
  // @@protoc_insertion_point(field_map:perceptronix.SparseMultinomialPerceptronProto.table)
  return table_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::perceptronix::SparseInnerTableProto >*
SparseMultinomialPerceptronProto::mutable_table() {
  // @@protoc_insertion_point(field_mutable_map:perceptronix.SparseMultinomialPerceptronProto.table)
  return table_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace perceptronix

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_linear_5fmodel_2eproto
